//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitalizacion2014.WSD2014 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSD2014.WSDatosSoap")]
    public interface WSDatosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ivkProcedimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Digitalizacion2014.WSD2014.cRetorno ivkProcedimiento(string procedimiento, string validar, string parametros, string BD, System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConexionesValidas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Digitalizacion2014.WSD2014.cRetorno ConexionesValidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/imagenesThumbnails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Digitalizacion2014.WSD2014.cRetorno imagenesThumbnails(string procedimiento, string validar, string parametros, string campoImg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerValor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string obtenerValor(string campo, string cadena, string separador, bool mayusculas);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cRetorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sResultadoField;
        
        private System.Data.DataSet dsField;
        
        private bool bOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sResultado {
            get {
                return this.sResultadoField;
            }
            set {
                this.sResultadoField = value;
                this.RaisePropertyChanged("sResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
                this.RaisePropertyChanged("ds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool bOk {
            get {
                return this.bOkField;
            }
            set {
                this.bOkField = value;
                this.RaisePropertyChanged("bOk");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDatosSoapChannel : Digitalizacion2014.WSD2014.WSDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDatosSoapClient : System.ServiceModel.ClientBase<Digitalizacion2014.WSD2014.WSDatosSoap>, Digitalizacion2014.WSD2014.WSDatosSoap {
        
        public WSDatosSoapClient() {
        }
        
        public WSDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Digitalizacion2014.WSD2014.cRetorno ivkProcedimiento(string procedimiento, string validar, string parametros, string BD, System.Data.DataSet ds) {
            return base.Channel.ivkProcedimiento(procedimiento, validar, parametros, BD, ds);
        }
        
        public Digitalizacion2014.WSD2014.cRetorno ConexionesValidas() {
            return base.Channel.ConexionesValidas();
        }
        
        public Digitalizacion2014.WSD2014.cRetorno imagenesThumbnails(string procedimiento, string validar, string parametros, string campoImg) {
            return base.Channel.imagenesThumbnails(procedimiento, validar, parametros, campoImg);
        }
        
        public string obtenerValor(string campo, string cadena, string separador, bool mayusculas) {
            return base.Channel.obtenerValor(campo, cadena, separador, mayusculas);
        }
    }
}
